# Let's migrate to v3
version: '2'
services:

  nginx:
    build: nginx
    ports:
      - "80:80"
    volumes_from:
      - backend
    
  backend:
    build: backend
    depends_on:
      - mysql
    env_file:
      - local.env
    volumes:
      - ./backend/presta:/app/backend
    restart: always

  mysql:
    image: mysql:5.6.39
    volumes:
      - presta_db_data:/var/lib/mysql
    env_file:
      - local.env
    # expose:
    #   - "3306"
    # for debug db replace expose with those lines
    ports:
      - 3306:3306
    # restart: always

volumes:
  presta_db_data:
    external: true